version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_JSON_SERVER_URL: http://json-server:5002
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_JSON_SERVER_URL: http://json-server:5002
    depends_on:
      - json-server

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json-server
    ports:
      - '5002:5002'
    volumes:
      - ./db.json:/app/db.json:ro
