version: '3.9'

services:
  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json-server
    restart: unless-stopped
    ports:
      - "5002:5002"
    volumes:
      - ./db.json:/app/db.json:ro
