/**
 * Service category ID (kebab-case)
 * Categories are dynamically loaded from service-categories.csv
 * Examples: 'pile-testing', 'soil-laboratory', 'material', etc.
 */
export type ServiceCategory = string;

/**
 * SEO metadata auto-generated from service data
 * Generated by scripts/parsers/seo-generator.ts
 */
export interface SEOMetadata {
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  ogTitle: string;
  ogDescription: string;
  ogUrl: string;
}

export interface Service {
  id: string;
  category: ServiceCategory;
  name: string;
  shortDescription: string;
  fullDescription: string;
  processSteps: string[];
  equipmentUsed: string[];
  typicalDeliverables: string[];
  media: {
    images: string[];
    heroImage?: string;
  };
  featured?: boolean;
  seo: SEOMetadata;
}
